@startuml
class main.com.myApp.dao.UserDao {
- DataSource dataSource
+ int save(UserModel)
}


class main.com.myApp.model.UserModel {
- String username
- String email
- String password
- String confirmPassword
}

class main.com.myApp.config.WebConfig {
+ void addResourceHandlers(ResourceHandlerRegistry)
}

class main.com.myApp.controller.HomeController {
- UserDao userDao
- Validator mvcValidator
+ void initBinder(WebDataBinder)
+ String HomePage(Model)
+ String showHomePage(Model)
+ String processForm(UserModel,BindingResult,Model)
+ String showTestForm()
}




org.springframework.web.servlet.config.annotation.WebMvcConfigurer <|.. main.com.myApp.config.WebConfig
@enduml